# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
---
aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2.1
jobs:
  build:
    machine: true
    branches:
      ignore: gh-pages
    steps:
      - run: echo "Skipping tests on gh-pages branch"
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "shubhamtatvamasi@gmail.com"
            git config --global user.name "Shubham Tatvamasi"
            echo "machine github.com login ShubhamTatvamasi password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=ShubhamTatvamasi yarn run publish-gh-pages

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - deploy-website:
        filters: *filter-only-master
...
